---
title: "Analysis"
author: "Jennifer Rogers"
date: "8/23/2021"
output: html_document
---
 
 in this script we combine the biolgoical data with the temperature data and with the habitat data


```{r}
library(sf)
library(tidyverse)
library(corrplot)
library(RColorBrewer)
library(lubridate)
```

here we summarize the bio data

```{r}
bio <- st_read("MassWildlife_EAS_combined_results.shp")
bio$date <- ymd(bio$date)


#what streams were sampled and when
strms <- bio %>% 
  filter(source == "EAS") %>% 
  mutate(stream = gsub("([^A-Za-z])+", "", x = site)) %>%
  data.frame() %>% 
  group_by(season, stream) %>% 
  summarise(count = n()) %>% 
  pivot_wider(names_from = season, values_from = count)
write.csv(strms, file = "final_figs_tables/sites.csv")

unique(strms$stream) #"MLB"  "BEBT" "BEB"  "POB"  "THB"  "GEB"  "GEBT" "PUBT" "PUB"  "PTB"  "PTBT" "MMB"  "MMBT" "THBT"


#streams we identified with brook trout eDNA 
edna <- bio %>% 
  filter(source == "EAS",
         occurrence == 1) %>% 
  mutate(stream = substr(site,1,3)) %>% 
  unique() #for some reason PTBT02 in spring has two records..
  
unique(edna$stream)

edna <- edna %>% 
  data.frame() %>% 
  dplyr::select(-geometry) %>% 
  group_by(season, stream,) %>% 
  summarise(count = n()) %>% 
  pivot_wider(names_from = season, values_from = count)
write.csv(edna, file = "final_figs_tables/positiveeDNA.csv")


#what streams previously had been identified as having trout from mass wildlife

dat <- bio %>% 
  filter(source == "MassWildlife")


```



We describe the culvert data
```{r}
cvt <- shapefile("culvert.shp")
unique(cvt$Stream)

#number of culverts by stream and severity
dat <- cvt %>%
  data.frame() %>% 
  group_by(Stream, Aqt_P_S) %>% 
  summarise(count = n()) %>% 
  ungroup() %>% 
  pivot_wider(names_from = Aqt_P_S, values_from = count) %>% 
  dplyr::select(1, 5,4,3,2,6)
dat[is.na(dat)] <- 0
write.csv(dat, file = "final_figs_tables/culvert_scores.csv")


#list of culverts on eDNA positive streams
rmv <- cvt %>% 
  filter(Stream %in% c("Beaver Brook", "Germany Brook", "Ponkapoag Brook", "Pine Tree Brook", "Traphole Brook"),
         Aqt_P_S %in% c("Significant Barrier", "Moderate Barrier", "Minor Barrier")) %>% 
  dplyr::select("Twn_Cnt",  "Stream" ,  "Road", "Wgh_C_S", "Aqt_P_S") %>% 
  arrange(Wgh_C_S) %>% 
  unique()
names(rmv) <- c("Town", "Stream", "Road Crossing", "Score", "Grade", "Location")
write.csv(rmv, file = "final_figs_tables/priority culverts.csv")


```
In this chunk we describe the habitat data


```{r}

load("habitat.RData")
load("DissolvedO2.RData")
DissOxy <- DissOxy %>% 
  dplyr::select(site, date, DO_mgl, DO_perc_sat, Temp_C)
habitat <- left_join(habitat, DissOxy, by = c("site", "date"))



#table of how many months we got to each site
hab <- habitat %>% 
  dplyr::select(site, month) %>% 
  unique() %>%
  group_by(site) %>% 
  summarize(count = n())


#Average the measurements from each site 
hab <- habitat %>% 
  group_by(site) %>% 
  summarise(depth = max(depth_cm),
            width = mean(wetted_width_m),
            LWD = sum(LWD),
            cover = max(canopy_cov_perc),
            complexity_type = length(unique(habitat)),
            complexity_num = length(habitat),
            DO = mean(DO_mgl))
hab$stream <- substring(hab$site, 1, 3)

#plot depth by month for each site within a waterbody
ggplot(data = habitat, mapping = aes(x =date, y = DO_mgl))+
  geom_point()+
  geom_line()+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size = 13),
        axis.title = element_text(size = 18),
        panel.border = element_rect(color = "black", fill = NA),
        strip.text.x = element_text(size = 14))+
  facet_wrap(~site)+
  labs(y = "Dissolved Oxygen (mg/l)", x = "Date")+
  geom_hline(yintercept = 6, color = "red", linetype = "dashed")
ggsave(plot = last_plot(), filename = "final_figs_tables/MnthlyDO.png", width = 10, height = 6, units = "in", dpi = 300)


#table of sites with coarse dominant and subdominate substrate
df <- habitat %>% 
  filter(dom_sub %in% c("gravel", "cobble") & subdom_sub %in% c("gravel", "cobble", "boulder"))
unique(df$site)

df <- habitat %>% 
  filter(habitat == "riffle")
unique(df$site)




ggplot(habitat[habitat$month == 6,], aes(x=habitat)) + 
    geom_bar()+
  facet_wrap(~site)


bio <- st_read("MassWildlife_EAS_combined_results.shp")
bio$year <- year(bio$date)


dat <- left_join(bio, habitat, by = c("site", "season", "year")) %>% 
  filter(!is.na(site),
         !is.na(max7max),
         !is.na(date))




```


Here we join the bio data with the temperature data and use a regression model to predict which sites should have trout based on temperature
```{r}
#first get the date range of each logger
load('StrmTempMetrics_2020_2021.RData')
load('StrnTemp_EAS_2020_2021.RData')

temps2 <- temps %>% 
  mutate(year = year(Date)) %>% 
  group_by(site, year) %>% 
  summarise(min = min(Date), 
            max = max(Date)) %>% 
  ungroup() %>% 
  mutate(min = substr(min, 0, 10),
         max = substr(max, 0, 10)) %>% 
  unite(col = "range", min, max, sep = " - " ) %>% 
  pivot_wider(names_from = year, values_from = range)

temps$stream <- substr(temps$site, 1,3)


#table of max7max
m <- metrics %>% 
  dplyr::select(site, season, max7max) %>% 
  pivot_wider(values_from = max7max, names_from = season) %>%
  group_by(site) %>% #some sites had data from spring and summer for two years and we want the average
  summarize(spring = round(mean(spring),2),
         summer = round(mean(summer),2))%>% 
  arrange(site)
write.csv(m, file = "final_figs_tables/max7max.csv")

ggplot(data = metrics, mapping = aes(x = site, y = max7avg, fill=season))+
  geom_bar(stat = "identity", position = "dodge")+
  scale_fill_manual(values=c("#00BA38", "#F8766D"))+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size = 13),
        axis.title = element_text(size = 18),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA),
        strip.text.x = element_text(size = 14))+
  facet_wrap(~year, nrow = 2)+
  geom_hline(yintercept = 20, color = "red", linetype = "dashed")+
  labs(y = "Maximum 7-day average (°C)", x = "Site ID", fill ="Season")
ggsave(plot = last_plot(), filename = "final_figs_tables/max7avg.png", width = 10, height = 6, units = "in", dpi = 300)



#bind with bio data
bio <- st_read("MassWildlife_EAS_combined_results.shp")
bio$year <- year(bio$date)
temp <- load("StrmTempMetrics_2020_2021.RData")

dat <- left_join(bio, metrics, by = c("site", "season", "year")) %>% 
  filter(!is.na(site),
         !is.na(max7max),
         !is.na(date))

#correlations between temperature variables
m <- data.frame(dat) %>% 
  dplyr::select(10:17)
m <- cor(m)
corrplot(m, type="upper", order="hclust", method = "number",
         col=brewer.pal(n=8, name="RdYlBu"))


ggplot(data = dat, mapping = aes(x = as.factor(occurrence), y = max7avg))+
  geom_boxplot()+
  facet_wrap(~season)+
  theme(axis.text = element_text(size = 9),
        axis.title = element_text(size = 10),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA),
        strip.text.x = element_text(size = 10))+
  facet_wrap(~season)+
  labs(y = "Max. 7-day average (°C)", x = "Brook Trout Occurrence")
ggsave(plot = last_plot(), filename = "final_figs_tables/occurrence_max7avg.png", width = 5, height = 3, units = "in", dpi = 300)


ggplot(data = dat, mapping = aes(x = max7avg, y = occurrence))+
  geom_point()+
  scale_color_manual(values = c("#00BA38", "#F8766D"))+
  theme(axis.text = element_text(size = 9),
        axis.title = element_text(size = 10),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA))+
  labs(x = "Max. 7-day average (°C)", y = "Probability of Occurrence", color = "Season")+
  geom_smooth(method = "glm", 
    method.args = list(family = "binomial"), fullrange=TRUE)+
  geom_hline(yintercept = 0.5, color = "red", linetype = "dashed")
ggsave(plot = last_plot(), filename = "final_figs_tables/log_reg_max7avg.png", width = 5, height = 3, units = "in", dpi = 300)

#binomial regression
mdl <- summary(glm(occurrence ~ max7avg, family="binomial", data = dat))

#get x value for P = 0.5
(log(.5/(1-.5)) - coef(mdl)[1])/coef(mdl)[2]
#18.8939

#join to habitat data
dat <- dat %>% 
  left_join(hab, by = "site") %>% 
  filter(!is.na(cover))

#look at canopy cover and temeprature
ggplot(data = dat, mapping = aes(x = as.factor(occurrence), y = complexity_num))+
  geom_boxplot()

ggplot(data = dat, mapping = aes(x = max7avg, y = depth))+
  geom_point()+
  geom_smooth(method = "lm")




```

